server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service: /upload/** # 将商品微服务映射到/item/**
    user-service: /user/** # 将用户微服务映射到/item/**
    auth-service: /auth/** # 用户授权中心
    cart-service: /cart/** # 购物车服务
  add-host-header: true # 携带请求本身的host头信息
  sensitive-headers: # 禁止使用头信息，设置为null，否则set-cookie无效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
ly:
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
  jwt:
    pubKeyPath: D:/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://api.leyou.com
    allowCredentials: true
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
      - PATCH
    maxAge: 3600
    filterPath: /**
    allowedHeaders:
      - "*"